### PR TITLE
Fix issues with update lifecycle. Resolves #121.

### LINKED ISSUE #121: Lastest Version Can't Update Single-Spa-React Component Props
image

Hi, Author

Background：
1. When User Update Parcel Custom Props，HOC Component Entry componentDidUpdate lifecycle， 
2. Using Promise Queue，To Update Single-Spa-React Componont where Provider Product。 

Problem：
1. When Do Update Function，No Promise Return To Finish，Leader To Next Promise(Update Operate) Can't Work

Solution:
1. May be Use whenFinished Function When Render Callback

### PR DESCRIPTION
**Pull request by joeldenning**
See #121

### CODE REVIEW

File: src/single-spa-react.js [hunk 1]
```diff
@@ -326,17 +341,14 @@ function getElementToRender(opts, props, mountFinished) {
...
   SingleSpaRoot.prototype.componentDidMount = function () {
-    this.mounted = true;
     setTimeout(this.props.mountFinished);
   };
   SingleSpaRoot.prototype.componentWillUnmount = function () {
     setTimeout(this.props.unmountFinished);
   };
   SingleSpaRoot.prototype.render = function () {
     // componentDidUpdate doesn't seem to be called during root.render() for updates
-    if (this.mounted) {
```
Comment (joeldenning) [inline src/single-spa-react.js:337]: I was having issues with the `this.mounted` - since it's not on `this.state` maybe new versions of react were not keeping that property there. So I just removed it, since calling `updateFinished` is a no-op if the component has never updated.

**Review by TheMcMurder — APPROVED** [review]
Looks good to me

**Review by rudavko — APPROVED** [review]
Looks good to me

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-react/releases/tag/v4.4.0
