### PR TITLE
Fixing issue with customProps prop. Resolves #82.

### LINKED ISSUE #82: Passing customProps to Micro application with Parcel breaks the mounting phase
**Describe the bug or question**
In the [lifecycle documentation](https://single-spa.js.org/docs/building-applications#lifecyle-props), the lifecycle props are said to certainly contain a customProps object, however, when we load an application as a Parcel, `customProps` field is undefined. In fact, setting `customProps` on `parcelProps` actually breaks the micro application.

It works when I don't pass customProps field though, and pass with another name instead like this:

```
singleSpa.mountRootParcel(component, {
   domElement: document.getElementById("element-id"),
   ourCustomProps: { foo: "bar" },
   });
```

So I am unsure what I am doing wrong there.

**To Reproduce**

pass `customProps` to parcel as

```
singleSpa.mountRootParcel(component, {
   domElement: document.getElementById("element-id"),
   customProps: { foo: "bar" },
   });
```

**Expected behavior**
The micro application is loaded, and `customProps = { foo: "bar" }` is present in the `props` in each of the lifecycles of the loaded application.

**Screenshots and/or console output**
`Error: parcel 'parcel-1' died in status SKIP_BECAUSE_BROKEN: single-spa-react was not given an application name as a prop, so it can't make a unique dom element container for the react application`

### PR DESCRIPTION
**Pull request by joeldenning**
See #82. The root cause of the problem here is that when we originally implemented parcels, the custom props were passed as a `customProps` property on the overall props object. After some feedback, we moved them to just be merged as top level properties. Then we changed single-spa-react to "work both ways." However, this caused confusion and a bug that was reported in #82. The older behavior for customProps was removed in https://github.com/single-spa/single-spa/releases/tag/v4.0.0-beta.6 and never made it into a stable release of single-spa. So I think it's fine to remove this behavior in single-spa-react without considering it a breaking change.

### CODE REVIEW

File: src/single-spa-react.js [hunk 1]
```diff
@@ -184,7 +184,6 @@ function atLeastReact16(React) {
 }
 
 function chooseDomElementGetter(opts, props) {
-  props = props && props.customProps ? props.customProps : props;
```
Comment (joeldenning) [inline src/single-spa-react.js:187]: This was added for backwards compatibility but now is considered a bug.

File: src/single-spa-react.test.js [hunk 2]
```diff
@@ -55,7 +55,7 @@ describe("single-spa-react", () => {
   });
 
   it(`mounts and unmounts a React component, passing through the single-spa props`, () => {
-    const props = { why: "hello", customProps: {} };
```
Comment (joeldenning) [inline src/single-spa-react.test.js:58]: The tests were originally written before the change to customProps that I described in the description of this PR

File: src/single-spa-react.test.js [hunk 3]
```diff
@@ -309,6 +307,22 @@ describe("single-spa-react", () => {
...
+      ReactDOM,
+      rootComponent,
+    });
+    const normalProps = { foo: "bar", name: "app1" };
+    await parcelConfig.bootstrap(normalProps);
+    await parcelConfig.mount(normalProps);
+
+    const unusualProps = { name: "app2", customProps: { foo: "bar" } };
+    await parcelConfig.bootstrap(unusualProps);
+    await parcelConfig.mount(unusualProps);
```
Comment (joeldenning) [inline src/single-spa-react.test.js:323]: This line threw an error before the fix
