### PR TITLE
fixing #67

### LINKED ISSUE #67: Instance issues when using the helper to generate parcels
Using helper parcels fail to correctly unmount:
https://codesandbox.io/s/quizzical-shadow-3t59x

Using manual mounting/unmounting parcels correctly unmount:
https://codesandbox.io/s/wizardly-dewdney-6yd5s

### PR DESCRIPTION
**Pull request by TheMcMurder**
Making it possible to reuse the same parcel config for multiple parcels This should fix #67

### CODE REVIEW

File: src/single-spa-react.js [hunk 1]
```diff
@@ -97,15 +98,15 @@ function mount(opts, props) {
...
+    opts.domElements[props.name] = domElement
   })
 }
 
 function unmount(opts, props) {
   return Promise
     .resolve()
     .then(() => {
-      opts.ReactDOM.unmountComponentAtNode(opts.domElement);
+      opts.ReactDOM.unmountComponentAtNode(opts.domElements[props.name]);
```
Comment (joeldenning) [inline src/single-spa-react.js]: Maybe clean up memory leak:

```js
delete opts.domElements[props.name]
```
